In [118]:
import numpy as np

In [119]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [120]:
%%time
for _ in range(20):
    my_arr2 = my_arr * 2


CPU times: total: 46.9 ms
Wall time: 42 ms


In [121]:
%%time
for _ in range(20):
    my_list2 = [x * 2 for x in my_list]


CPU times: total: 1.7 s
Wall time: 1.73 s


In [122]:
def py_sum():
    a = [0, 1, 2, 3, 4]
    b = [9, 8, 7, 6, 5]
    c = []
    for i in range(len(a)):
        c.append(a[i] ** 2 + b[i] ** 3)
    return c


print(py_sum())

[729, 513, 347, 225, 141]


In [123]:
import numpy as np


def np_sum():
    a = np.array([0, 1, 2, 3, 4])
    b = np.array([9, 8, 7, 6, 5])
    c = a ** 2 + b ** 3
    return c


print(np_sum())


[729 513 347 225 141]


In [124]:
a = np.array([[0, 1, 2, 3, 4], [9, 8, 7, 6, 5]])
a

array([[0, 1, 2, 3, 4],
       [9, 8, 7, 6, 5]])

In [125]:
np.array([[0, 1, 2, 3, 4], [9, 8, 7, 6, 5]])

array([[0, 1, 2, 3, 4],
       [9, 8, 7, 6, 5]])

In [126]:
import numpy as np

a = np.array([[0, 1, 2, 3, 4], [9, 8, 7, 6, 5]])
print(a.ndim, a.shape, a.size, a.dtype, a.itemsize)


2 (2, 5) 10 int32 4


In [127]:
x = np.array([1, 2, 3, 4])
x


array([1, 2, 3, 4])

In [128]:
x = np.array((1, 2, 3, 4))
x


array([1, 2, 3, 4])

In [129]:
x = np.array([(1, 2, 3, 4), (1, 2, 3, 8)])
x


array([[1, 2, 3, 4],
       [1, 2, 3, 8]])

In [130]:
import numpy as np

np.empty([3, 2], dtype=int)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [131]:
np.linspace(1, 21, 9, endpoint=True, dtype=int)

array([ 1,  3,  6,  8, 11, 13, 16, 18, 21])

In [132]:
np.logspace(0, 9, 10, base=3, dtype=np.float16)


array([1.000e+00, 3.000e+00, 9.000e+00, 2.700e+01, 8.100e+01, 2.430e+02,
       7.290e+02, 2.188e+03, 6.560e+03, 1.968e+04], dtype=float16)

In [133]:
import numpy as np

a = np.linspace(1, 20, 9, endpoint=False, dtype=int)
b = np.logspace(0, 9, 10, base=2, dtype=int)
c = np.concatenate((a, b))

In [134]:
import numpy as np

a = np.ones((2, 3, 4), dtype=np.int32)
a.reshape((3, 8))

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [135]:
import numpy as np

a = np.ones((2, 3, 4), dtype=np.int32)

a.resize((3, 8))
a


array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [136]:
import numpy as np

a = np.array(
    [
        [[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]],
        [[2, 2, 2, 2], [2, 2, 2, 2], [2, 2, 2, 2]]
    ]
)

a.swapaxes(0, 1)

array([[[1, 1, 1, 1],
        [2, 2, 2, 2]],

       [[1, 1, 1, 1],
        [2, 2, 2, 2]],

       [[1, 1, 1, 1],
        [2, 2, 2, 2]]])

In [137]:
import numpy as np

a = np.array(
    [
        [[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]],
        [[2, 2, 2, 2], [2, 2, 2, 2], [2, 2, 2, 2]]
    ]
)

a.flatten()

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [138]:
import numpy as np

a = np.ones((2, 3, 4), dtype=np.int32)
a

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [139]:
import numpy as np

a = np.ones((2, 3, 4), dtype=np.int32)

In [140]:
import numpy as np

a = np.ones((2, 3, 4), dtype=np.int32)
b = a.astype(np.float)

b

C:\Users\yaojie\AppData\Local\Temp\ipykernel_4764\1517402046.py:4: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  b = a.astype(np.float)


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [141]:
import numpy as np

a = np.full((2, 3, 4), 25, dtype=np.int32)
a


array([[[25, 25, 25, 25],
        [25, 25, 25, 25],
        [25, 25, 25, 25]],

       [[25, 25, 25, 25],
        [25, 25, 25, 25],
        [25, 25, 25, 25]]])

In [142]:
import numpy as np

a = np.full((2, 3, 4), 25, dtype=np.int32)
a

a.tolist()


[[[25, 25, 25, 25], [25, 25, 25, 25], [25, 25, 25, 25]],
 [[25, 25, 25, 25], [25, 25, 25, 25], [25, 25, 25, 25]]]

In [143]:
import numpy as np

data = np.array([1, 2, 3])
print('输出数组：', data)
print(data[0], data[1], data[0:2], data[1:])

输出数组： [1 2 3]
1 2 [1 2] [2 3]


In [144]:
import numpy as np

data = np.array([1, 2, 3])
print(data.max(), data.min(), data.sum())

3 1 6


In [145]:
import numpy as np

data = np.array([[1, 2], [3, 4], [5, 6]])
print(data)
print(data[0, 1])
print(data[1:3])
print(data[0:2, 0])

[[1 2]
 [3 4]
 [5 6]]
2
[[3 4]
 [5 6]]
[1 3]


In [146]:
import numpy as np

data = np.array([[1, 2], [3, 4], [5, 6]])
print(data.max(), data.min(), data.sum())


6 1 21


In [147]:
print(data.max(axis=0), data.max(axis=1))

[5 6] [2 4 6]


In [148]:
import numpy as np

x = np.array([[1, 2], [3, 4], [5, 6]])
y = x[[0, 1, 2], [0, 1, 0]]
print(x, y)


[[1 2]
 [3 4]
 [5 6]] [1 4 5]


In [149]:
import numpy as np

x = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [9, 10, 11]
])

rows = np.array([[0, 0], [3, 3]])
cols = np.array([[0, 2], [0, 2]])

x[rows, cols]

array([[ 0,  2],
       [ 9, 11]])

In [150]:
import numpy as py

x = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [9, 10, 11]
])
print(x[x > 5])

[ 6  7  8  9 10 11]


In [151]:
import numpy as py

a = np.array([np.nan, 1, 2, np.nan, 3, 4, 5])
print(a[~np.isnan(a)])

[1. 2. 3. 4. 5.]


In [152]:
import numpy as py

a = np.array([1, 2 + 6j, 5, 3.5 + 5j])
print(a[np.iscomplex(a)])

[2. +6.j 3.5+5.j]


In [153]:
import numpy as np

x = np.arange(32).reshape(8, 4)
x[[4, 2, 1, 7]]

array([[16, 17, 18, 19],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [28, 29, 30, 31]])

In [154]:
import numpy as np

x = np.arange(32).reshape((8, 4))
x[[-4, -2, -1, -7]]

array([[16, 17, 18, 19],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [ 4,  5,  6,  7]])

In [155]:
import numpy as np

print(x)
print(x[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [156]:
import numpy as np

a = np.arange(8)
print(a, '\n')

b = a.reshape(4, 2)
print(b, '\n')

[0 1 2 3 4 5 6 7] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]] 



In [157]:
import numpy as np

a = np.arange(4).reshape(2, 2)
for row in a:
    print(row)

[0 1]
[2 3]


In [158]:
import numpy as np

a = np.arange(4).reshape(2, 2)
for row in a:
    print(row)

for item in a.flat:
    print(item)

[0 1]
[2 3]
0
1
2
3


In [159]:
import numpy as np

a = np.arange(8).reshape(2, 4)
print(a)

print(a.flatten())
print(a.flatten(order='F'))

[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3 4 5 6 7]
[0 4 1 5 2 6 3 7]


In [160]:
import numpy as np

a = np.arange(8).reshape(2, 4)
print(a)

print(a.ravel())

print(a.ravel(order='F'))

[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3 4 5 6 7]
[0 4 1 5 2 6 3 7]


In [161]:
import numpy as np

a = np.arange(12).reshape(3, 4)
print(a)

print(np.transpose(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [162]:
import numpy as np

a = np.arange(12).reshape(3, 4)

print(a)
print(a.T)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [163]:
import numpy as np

a = np.arange(8).reshape(2, 2, 2)
print(a)
print(np.rollaxis(a, 2))
print(np.rollaxis(a, 2, 1))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]
[[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]]


In [164]:
import numpy as np

a = np.arange(8).reshape(2, 2, 2)
print(a)
print(np.swapaxes(a, 2, 0))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


In [165]:
import numpy as np

x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])

b = np.broadcast(x, y)
r, c = b.iters

print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))

1 4
1 5
1 6
2 4
2 5
2 6


In [166]:
import numpy as np

a = np.arange(4).reshape(1, 4)

print(a)

print(np.broadcast_to(a, (4, 4)))

[[0 1 2 3]]
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [167]:
import numpy as np

x = np.array(([1, 2], [3, 4]))

print(x)
y = np.expand_dims(x, axis=0)
print(y)
print(x.shape, y.shape)

y = np.expand_dims(x, axis=1)
print(y)
print(x.ndim, y.ndim)

print(x.shape, y.shape)

[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]]
(2, 2) (1, 2, 2)
[[[1 2]]

 [[3 4]]]
2 3
(2, 2) (2, 1, 2)


In [168]:
import numpy as np

x = np.arange(9).reshape(1, 3, 3)

print('数组 x：')
print(x)
print('\n')
y = np.squeeze(x)

print('数组 y：')
print(y)
print('\n')

print('数组 x 和 y 的形状：')
print(x.shape, y.shape)

数组 x：
[[[0 1 2]
  [3 4 5]
  [6 7 8]]]


数组 y：
[[0 1 2]
 [3 4 5]
 [6 7 8]]


数组 x 和 y 的形状：
(1, 3, 3) (3, 3)


In [169]:
import numpy as np

a = np.array([[1, 2], [3, 4]])

print('第一个数组：')
print(a)
print('\n')

b = np.array([[5, 6], [7, 8]])
print('第二个数组：')
print(b)
print('\n')

print('沿着 0 连接两个数组：')
print(np.concatenate((a, b)))
print('\n')

print('沿着 1 连接两个数组：')
print(np.concatenate((a, b), axis=1))

第一个数组：
[[1 2]
 [3 4]]


第二个数组：
[[5 6]
 [7 8]]


沿着 0 连接两个数组：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


沿着 1 连接两个数组：
[[1 2 5 6]
 [3 4 7 8]]


In [170]:
import numpy as py

a = np.array([[1, 2], [3, 4]])

print('第一个数组：')
print(a)
print('\n')

b = np.array([[5, 6], [7, 8]])

print('第二个数组：')
print(b)
print('\n')

print('沿着 0 堆叠两个数组：')
print(np.stack((a, b), 0))
print('\n')

print('沿轴 1 堆叠两个数组：')
print(np.stack((a, b), 1))

第一个数组：
[[1 2]
 [3 4]]


第二个数组：
[[5 6]
 [7 8]]


沿着 0 堆叠两个数组：
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


沿轴 1 堆叠两个数组：
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [171]:
import numpy as np

a = np.array([[1, 2], [3, 4]])

print('第一个数组：')
print(a)
print('\n')
b = np.array([[5, 6], [7, 8]])

print('第二个数组：')
print(b)
print('\n')

print('水平堆叠')
c = np.hstack((a, b))
print(c)
print('\n')

第一个数组：
[[1 2]
 [3 4]]


第二个数组：
[[5 6]
 [7 8]]


水平堆叠
[[1 2 5 6]
 [3 4 7 8]]




In [172]:
import numpy as np

a = np.array([[1, 2], [3, 4]])

print('第一个数组：')
print(a)
print('\n')

b = np.array([[5, 6], [7, 8]])
print('第二个数组：')
print(b)
print('\n')

print('数值堆叠：')
c = np.vstack((a, b))
print(c)

第一个数组：
[[1 2]
 [3 4]]


第二个数组：
[[5 6]
 [7 8]]


数值堆叠：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [173]:
import numpy as np

a = np.arange(9)

print('第一个数组：')
print(a)
print('\n')

print('将数组分为三个大小相同的子数组：')
b = np.split(a, 3)
print(b)
print('\n')

print('将数组在一维数组中表面的位置分隔：')
b = np.split(a, [4, 7])
print(b)

第一个数组：
[0 1 2 3 4 5 6 7 8]


将数组分为三个大小相同的子数组：
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


将数组在一维数组中表面的位置分隔：
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [174]:
import numpy as np

harr = np.floor(10 * np.random.random((2, 6)))
print('原数组：')
print(harr)

print('拆分后：')
print(np.hsplit(harr, 3))


原数组：
[[1. 0. 7. 2. 5. 7.]
 [8. 7. 2. 7. 7. 0.]]
拆分后：
[array([[1., 0.],
       [8., 7.]]), array([[7., 2.],
       [2., 7.]]), array([[5., 7.],
       [7., 0.]])]


In [175]:
import numpy as np

a = np.arange(16).reshape(4, 4)

print('原数组：')
print(a)
print('\n')

print('竖直分割：')
b = np.vsplit(a, 2)
print(b)


原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


竖直分割：
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [176]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print('第一个数组：')
print(a)
print('\n')

print('第一个数组的形状：')
print(a.shape)
print('\n')

b = np.resize(a, (3, 2))
print('第二个数组：')
print(b)
print('\n')

print('第二个数组的形状：')
print(b.shape)
print('\n')

print('修改第二个数组的大小：')
b = np.resize(a, (3, 3))
print(b)

第一个数组：
[[1 2 3]
 [4 5 6]]


第一个数组的形状：
(2, 3)


第二个数组：
[[1 2]
 [3 4]
 [5 6]]


第二个数组的形状：
(3, 2)


修改第二个数组的大小：
[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [177]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print('第一个数组：')
print(a)
print('\n')

print('向数组添加元素：')
print(np.append(a, [7, 8, 9]))
print('\n')

print('沿轴 0 添加元素：')
print(np.append(a, [[7, 8, 9]], axis=0))
print('\n')

print('沿轴 1 添加元素：')
print(np.append(a, [[5, 5, 5], [7, 8, 9]], axis=1))

第一个数组：
[[1 2 3]
 [4 5 6]]


向数组添加元素：
[1 2 3 4 5 6 7 8 9]


沿轴 0 添加元素：
[[1 2 3]
 [4 5 6]
 [7 8 9]]


沿轴 1 添加元素：
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [178]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])

print('原数组：')
print(a)
print('\n')

print('未传递 Axis 参数，在插入之前数字会被展开')
print(np.insert(a, 3, [11, 12]))
print('\n')

print('传递了 axis 参数，会广播值数值来配输入数组')
print('沿着 0 广播：')
print(np.insert(a, 1, [11], axis=0))
print('\n')

print('沿轴 1 广播：')
print(np.insert(a, 1, 11, axis=1))

原数组：
[[1 2]
 [3 4]
 [5 6]]


未传递 Axis 参数，在插入之前数字会被展开
[ 1  2  3 11 12  4  5  6]


传递了 axis 参数，会广播值数值来配输入数组
沿着 0 广播：
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


沿轴 1 广播：
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [179]:
import numpy as np

a = np.arange(12).reshape(3, 4)

print('第一个数组：')
print(a)
print('\n')

print('未传递 axis 参数，在插入之前输入输入会被展开')
print(np.delete(a, 5))
print('\n')

print('删除第二列：')
print(np.delete(a, 1, axis=1))
print('\n')

print('包含从数组中删除的替代值的切片：')
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np.delete(a, np.s_[::2]))

第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


未传递 axis 参数，在插入之前输入输入会被展开
[ 0  1  2  3  4  6  7  8  9 10 11]


删除第二列：
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


包含从数组中删除的替代值的切片：
[ 2  4  6  8 10]


In [180]:
import numpy as np

a = np.array([5, 2, 6, 2, 7, 5, 6, 8, 2, 90])

print('第一个数组：')
print(a)
print('\n')

print('第一个数组的去重值：')
u = np.unique(a)
print(u)
print('\n')

print('去重数组的索引数组：')
u, indices = np.unique(a, return_index=True)
print(indices)
print('\n')

print('我们可以看到每个和原数组下标对应的数值：')
print(a)
print('\n')

print('去重数组的下标：')
u, indices = np.unique(a, return_inverse=True)
print(u)
print('\n')

print('下标为：')
print(indices)
print('\n')

print('使用下标重构原数组：')
print(u[indices])
print('\n')

print('返回去重元素的重复数量：')
u, indices = np.unique(a, return_index=True)
print(u)
print(indices)

第一个数组：
[ 5  2  6  2  7  5  6  8  2 90]


第一个数组的去重值：
[ 2  5  6  7  8 90]


去重数组的索引数组：
[1 0 2 4 7 9]


我们可以看到每个和原数组下标对应的数值：
[ 5  2  6  2  7  5  6  8  2 90]


去重数组的下标：
[ 2  5  6  7  8 90]


下标为：
[1 0 2 0 3 1 2 4 0 5]


使用下标重构原数组：
[ 5  2  6  2  7  5  6  8  2 90]


返回去重元素的重复数量：
[ 2  5  6  7  8 90]
[1 0 2 4 7 9]


In [181]:
import numpy as np

a = np.arange(6).reshape(3, 2)

print('初始数组：', '\n', a, '\n')
print('迭代数组：')

for x in np.nditer(a):
    print(x, end='.')


初始数组： 
 [[0 1]
 [2 3]
 [4 5]] 

迭代数组：
0.1.2.3.4.5.

In [182]:
a = np.arange(6).reshape(3, 2)

print('初始数组：', '\n', a, '\n')
print('以F形式进行迭代：')

for i in np.nditer(a, order='F'):
    print(i, end=',')

print('\n')

print('以 C 形式进行迭代：')
for i in np.nditer(a, order='C'):
    print(i, end=',')

初始数组： 
 [[0 1]
 [2 3]
 [4 5]] 

以F形式进行迭代：
0,2,4,1,3,5,

以 C 形式进行迭代：
0,1,2,3,4,5,

In [183]:
import numpy as np

a = np.arange(0, 60, 5).reshape(3, 4)

print('原始数组时：')
print(a)
print('\n')

for x in np.nditer(a, op_flags=['readwrite']):  #%%
    import numpy as np

原始数组时：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]




In [184]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [185]:
% % time
for _ in range(20):
    my_arr2 = my_arr * 2


UsageError: Line magic function `%` not found.


In [ ]:
% % time
for _ in range(20):
    my_list2 = [x * 2 for x in my_list]


In [ ]:
def py_sum():
    a = [0, 1, 2, 3, 4]
    b = [9, 8, 7, 6, 5]
    c = []
    for i in range(len(a)):
        c.append(a[i] ** 2 + b[i] ** 3)
    return c


print(py_sum())

In [ ]:
import numpy as np


def np_sum():
    a = np.array([0, 1, 2, 3, 4])
    b = np.array([9, 8, 7, 6, 5])
    c = a ** 2 + b ** 3
    return c


print(np_sum())


In [ ]:
a = np.array([[0, 1, 2, 3, 4], [9, 8, 7, 6, 5]])
a

In [ ]:
np.array([[0, 1, 2, 3, 4], [9, 8, 7, 6, 5]])

In [ ]:
import numpy as np

a = np.array([[0, 1, 2, 3, 4], [9, 8, 7, 6, 5]])
print(a.ndim, a.shape, a.size, a.dtype, a.itemsize)


In [ ]:
x = np.array([1, 2, 3, 4])
x


In [ ]:
x = np.array((1, 2, 3, 4))
x


In [ ]:
x = np.array([(1, 2, 3, 4), (1, 2, 3, 8)])
x


In [ ]:
import numpy as np

np.empty([3, 2], dtype=int)

In [ ]:
np.linspace(1, 21, 9, endpoint=True, dtype=int)

In [ ]:
np.logspace(0, 9, 10, base=3, dtype=np.float16)


In [ ]:
import numpy as np

a = np.linspace(1, 20, 9, endpoint=False, dtype=int)
b = np.logspace(0, 9, 10, base=2, dtype=int)
c = np.concatenate((a, b))

In [ ]:
import numpy as np

a = np.ones((2, 3, 4), dtype=np.int32)
a.reshape((3, 8))

In [ ]:
import numpy as np

a = np.ones((2, 3, 4), dtype=np.int32)

a.resize((3, 8))
a


In [ ]:
import numpy as np

a = np.array(
    [
        [[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]],
        [[2, 2, 2, 2], [2, 2, 2, 2], [2, 2, 2, 2]]
    ]
)

a.swapaxes(0, 1)

In [ ]:
import numpy as np

a = np.array(
    [
        [[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]],
        [[2, 2, 2, 2], [2, 2, 2, 2], [2, 2, 2, 2]]
    ]
)

a.flatten()

In [ ]:
import numpy as np

a = np.ones((2, 3, 4), dtype=np.int32)
a

In [ ]:
import numpy as np

a = np.ones((2, 3, 4), dtype=np.int32)

In [ ]:
import numpy as np

a = np.ones((2, 3, 4), dtype=np.int32)
b = a.astype(np.float)

b

In [ ]:
import numpy as np

a = np.full((2, 3, 4), 25, dtype=np.int32)
a


In [ ]:
import numpy as np

a = np.full((2, 3, 4), 25, dtype=np.int32)
a

a.tolist()


In [ ]:
import numpy as np

data = np.array([1, 2, 3])
print('输出数组：', data)
print(data[0], data[1], data[0:2], data[1:])

In [ ]:
import numpy as np

data = np.array([1, 2, 3])
print(data.max(), data.min(), data.sum())

In [ ]:
import numpy as np

data = np.array([[1, 2], [3, 4], [5, 6]])
print(data)
print(data[0, 1])
print(data[1:3])
print(data[0:2, 0])

In [ ]:
import numpy as np

data = np.array([[1, 2], [3, 4], [5, 6]])
print(data.max(), data.min(), data.sum())


In [ ]:
print(data.max(axis=0), data.max(axis=1))

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 4], [5, 6]])
y = x[[0, 1, 2], [0, 1, 0]]
print(x, y)


In [ ]:
import numpy as np

x = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [9, 10, 11]
])

rows = np.array([[0, 0], [3, 3]])
cols = np.array([[0, 2], [0, 2]])

x[rows, cols]

In [ ]:
import numpy as py

x = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [9, 10, 11]
])
print(x[x > 5])

In [ ]:
import numpy as py

a = np.array([np.nan, 1, 2, np.nan, 3, 4, 5])
print(a[~np.isnan(a)])

In [ ]:
import numpy as py

a = np.array([1, 2 + 6j, 5, 3.5 + 5j])
print(a[np.iscomplex(a)])

In [ ]:
import numpy as np

x = np.arange(32).reshape(8, 4)
x[[4, 2, 1, 7]]

In [ ]:
import numpy as np

x = np.arange(32).reshape((8, 4))
x[[-4, -2, -1, -7]]

In [ ]:
import numpy as np

print(x)
print(x[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])])


In [ ]:
import numpy as np

a = np.arange(8)
print(a, '\n')

b = a.reshape(4, 2)
print(b, '\n')

In [ ]:
import numpy as np

a = np.arange(4).reshape(2, 2)
for row in a:
    print(row)

In [ ]:
import numpy as np

a = np.arange(4).reshape(2, 2)
for row in a:
    print(row)

for item in a.flat:
    print(item)

In [ ]:
import numpy as np

a = np.arange(8).reshape(2, 4)
print(a)

print(a.flatten())
print(a.flatten(order='F'))

In [ ]:
import numpy as np

a = np.arange(8).reshape(2, 4)
print(a)

print(a.ravel())

print(a.ravel(order='F'))

In [ ]:
import numpy as np

a = np.arange(12).reshape(3, 4)
print(a)

print(np.transpose(a))

In [ ]:
import numpy as np

a = np.arange(12).reshape(3, 4)

print(a)
print(a.T)


In [ ]:
import numpy as np

a = np.arange(8).reshape(2, 2, 2)
print(a)
print(np.rollaxis(a, 2))
print(np.rollaxis(a, 2, 1))

In [ ]:
import numpy as np

a = np.arange(8).reshape(2, 2, 2)
print(a)
print(np.swapaxes(a, 2, 0))

In [ ]:
import numpy as np

x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])

b = np.broadcast(x, y)
r, c = b.iters

print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))

In [ ]:
import numpy as np

a = np.arange(4).reshape(1, 4)

print(a)

print(np.broadcast_to(a, (4, 4)))

In [ ]:
import numpy as np

x = np.array(([1, 2], [3, 4]))

print(x)
y = np.expand_dims(x, axis=0)
print(y)
print(x.shape, y.shape)

y = np.expand_dims(x, axis=1)
print(y)
print(x.ndim, y.ndim)

print(x.shape, y.shape)

In [ ]:
import numpy as np

x = np.arange(9).reshape(1, 3, 3)

print('数组 x：')
print(x)
print('\n')
y = np.squeeze(x)

print('数组 y：')
print(y)
print('\n')

print('数组 x 和 y 的形状：')
print(x.shape, y.shape)

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])

print('第一个数组：')
print(a)
print('\n')

b = np.array([[5, 6], [7, 8]])
print('第二个数组：')
print(b)
print('\n')

print('沿着 0 连接两个数组：')
print(np.concatenate((a, b)))
print('\n')

print('沿着 1 连接两个数组：')
print(np.concatenate((a, b), axis=1))

In [ ]:
import numpy as py

a = np.array([[1, 2], [3, 4]])

print('第一个数组：')
print(a)
print('\n')

b = np.array([[5, 6], [7, 8]])

print('第二个数组：')
print(b)
print('\n')

print('沿着 0 堆叠两个数组：')
print(np.stack((a, b), 0))
print('\n')

print('沿轴 1 堆叠两个数组：')
print(np.stack((a, b), 1))

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])

print('第一个数组：')
print(a)
print('\n')
b = np.array([[5, 6], [7, 8]])

print('第二个数组：')
print(b)
print('\n')

print('水平堆叠')
c = np.hstack((a, b))
print(c)
print('\n')

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])

print('第一个数组：')
print(a)
print('\n')

b = np.array([[5, 6], [7, 8]])
print('第二个数组：')
print(b)
print('\n')

print('数值堆叠：')
c = np.vstack((a, b))
print(c)

In [ ]:
import numpy as np

a = np.arange(9)

print('第一个数组：')
print(a)
print('\n')

print('将数组分为三个大小相同的子数组：')
b = np.split(a, 3)
print(b)
print('\n')

print('将数组在一维数组中表面的位置分隔：')
b = np.split(a, [4, 7])
print(b)

In [ ]:
import numpy as np

harr = np.floor(10 * np.random.random((2, 6)))
print('原数组：')
print(harr)

print('拆分后：')
print(np.hsplit(harr, 3))


In [ ]:
import numpy as np

a = np.arange(16).reshape(4, 4)

print('原数组：')
print(a)
print('\n')

print('竖直分割：')
b = np.vsplit(a, 2)
print(b)


In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print('第一个数组：')
print(a)
print('\n')

print('第一个数组的形状：')
print(a.shape)
print('\n')

b = np.resize(a, (3, 2))
print('第二个数组：')
print(b)
print('\n')

print('第二个数组的形状：')
print(b.shape)
print('\n')

print('修改第二个数组的大小：')
b = np.resize(a, (3, 3))
print(b)

In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print('第一个数组：')
print(a)
print('\n')

print('向数组添加元素：')
print(np.append(a, [7, 8, 9]))
print('\n')

print('沿轴 0 添加元素：')
print(np.append(a, [[7, 8, 9]], axis=0))
print('\n')

print('沿轴 1 添加元素：')
print(np.append(a, [[5, 5, 5], [7, 8, 9]], axis=1))

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])

print('原数组：')
print(a)
print('\n')

print('未传递 Axis 参数，在插入之前数字会被展开')
print(np.insert(a, 3, [11, 12]))
print('\n')

print('传递了 axis 参数，会广播值数值来配输入数组')
print('沿着 0 广播：')
print(np.insert(a, 1, [11], axis=0))
print('\n')

print('沿轴 1 广播：')
print(np.insert(a, 1, 11, axis=1))

In [ ]:
import numpy as np

a = np.arange(12).reshape(3, 4)

print('第一个数组：')
print(a)
print('\n')

print('未传递 axis 参数，在插入之前输入输入会被展开')
print(np.delete(a, 5))
print('\n')

print('删除第二列：')
print(np.delete(a, 1, axis=1))
print('\n')

print('包含从数组中删除的替代值的切片：')
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np.delete(a, np.s_[::2]))

In [ ]:
import numpy as np

a = np.array([5, 2, 6, 2, 7, 5, 6, 8, 2, 90])

print('第一个数组：')
print(a)
print('\n')

print('第一个数组的去重值：')
u = np.unique(a)
print(u)
print('\n')

print('去重数组的索引数组：')
u, indices = np.unique(a, return_index=True)
print(indices)
print('\n')

print('我们可以看到每个和原数组下标对应的数值：')
print(a)
print('\n')

print('去重数组的下标：')
u, indices = np.unique(a, return_inverse=True)
print(u)
print('\n')

print('下标为：')
print(indices)
print('\n')

print('使用下标重构原数组：')
print(u[indices])
print('\n')

print('返回去重元素的重复数量：')
u, indices = np.unique(a, return_index=True)
print(u)
print(indices)

In [ ]:
import numpy as np

a = np.arange(6).reshape(3, 2)

print('初始数组：', '\n', a, '\n')
print('迭代数组：')

for x in np.nditer(a):
    print(x, end='.')


In [ ]:
a = np.arange(6).reshape(3, 2)

print('初始数组：', '\n', a, '\n')
print('以F形式进行迭代：')

for i in np.nditer(a, order='F'):
    print(i, end=',')

print('\n')

print('以 C 形式进行迭代：')
for i in np.nditer(a, order='C'):
    print(i, end=',')

In [ ]:
import numpy as np

a = np.arange(0, 60, 5).reshape(3, 4)

print('原始数组时：')
print(a)
print('\n')

for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = 2 * x
print('修改后的数组是：', '\n', a)

In [ ]:
import numpy as np

a = np.arange(0, 60, 5).reshape(3, 4)
print('原始数组是：', '\n', a, '\n')

print('修改后的数组是：')
for x in np.nditer(a, flags=['external_loop'], order='F'):
    print(x, end='.')
print('\n')
for x in np.nditer(a, flags=['f_index'], order='F'):  #%%
    import numpy as np

In [ ]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [ ]:
% % time
for _ in range(20):
    my_arr2 = my_arr * 2


In [ ]:
% % time
for _ in range(20):
    my_list2 = [x * 2 for x in my_list]


In [ ]:
def py_sum():
    a = [0, 1, 2, 3, 4]
    b = [9, 8, 7, 6, 5]
    c = []
    for i in range(len(a)):
        c.append(a[i] ** 2 + b[i] ** 3)
    return c


print(py_sum())

In [ ]:
import numpy as np


def np_sum():
    a = np.array([0, 1, 2, 3, 4])
    b = np.array([9, 8, 7, 6, 5])
    c = a ** 2 + b ** 3
    return c


print(np_sum())


In [ ]:
a = np.array([[0, 1, 2, 3, 4], [9, 8, 7, 6, 5]])
a

In [ ]:
np.array([[0, 1, 2, 3, 4], [9, 8, 7, 6, 5]])

In [ ]:
import numpy as np

a = np.array([[0, 1, 2, 3, 4], [9, 8, 7, 6, 5]])
print(a.ndim, a.shape, a.size, a.dtype, a.itemsize)


In [ ]:
x = np.array([1, 2, 3, 4])
x


In [ ]:
x = np.array((1, 2, 3, 4))
x


In [ ]:
x = np.array([(1, 2, 3, 4), (1, 2, 3, 8)])
x


In [ ]:
import numpy as np

np.empty([3, 2], dtype=int)

In [ ]:
np.linspace(1, 21, 9, endpoint=True, dtype=int)

In [ ]:
np.logspace(0, 9, 10, base=3, dtype=np.float16)


In [ ]:
import numpy as np

a = np.linspace(1, 20, 9, endpoint=False, dtype=int)
b = np.logspace(0, 9, 10, base=2, dtype=int)
c = np.concatenate((a, b))

In [ ]:
import numpy as np

a = np.ones((2, 3, 4), dtype=np.int32)
a.reshape((3, 8))

In [ ]:
import numpy as np

a = np.ones((2, 3, 4), dtype=np.int32)

a.resize((3, 8))
a


In [ ]:
import numpy as np

a = np.array(
    [
        [[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]],
        [[2, 2, 2, 2], [2, 2, 2, 2], [2, 2, 2, 2]]
    ]
)

a.swapaxes(0, 1)

In [ ]:
import numpy as np

a = np.array(
    [
        [[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]],
        [[2, 2, 2, 2], [2, 2, 2, 2], [2, 2, 2, 2]]
    ]
)

a.flatten()

In [ ]:
import numpy as np

a = np.ones((2, 3, 4), dtype=np.int32)
a

In [ ]:
import numpy as np

a = np.ones((2, 3, 4), dtype=np.int32)

In [ ]:
import numpy as np

a = np.ones((2, 3, 4), dtype=np.int32)
b = a.astype(np.float)

b

In [ ]:
import numpy as np

a = np.full((2, 3, 4), 25, dtype=np.int32)
a


In [ ]:
import numpy as np

a = np.full((2, 3, 4), 25, dtype=np.int32)
a

a.tolist()


In [ ]:
import numpy as np

data = np.array([1, 2, 3])
print('输出数组：', data)
print(data[0], data[1], data[0:2], data[1:])

In [ ]:
import numpy as np

data = np.array([1, 2, 3])
print(data.max(), data.min(), data.sum())

In [ ]:
import numpy as np

data = np.array([[1, 2], [3, 4], [5, 6]])
print(data)
print(data[0, 1])
print(data[1:3])
print(data[0:2, 0])

In [ ]:
import numpy as np

data = np.array([[1, 2], [3, 4], [5, 6]])
print(data.max(), data.min(), data.sum())


In [ ]:
print(data.max(axis=0), data.max(axis=1))

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 4], [5, 6]])
y = x[[0, 1, 2], [0, 1, 0]]
print(x, y)


In [ ]:
import numpy as np

x = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [9, 10, 11]
])

rows = np.array([[0, 0], [3, 3]])
cols = np.array([[0, 2], [0, 2]])

x[rows, cols]

In [ ]:
import numpy as py

x = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [9, 10, 11]
])
print(x[x > 5])

In [ ]:
import numpy as py

a = np.array([np.nan, 1, 2, np.nan, 3, 4, 5])
print(a[~np.isnan(a)])

In [ ]:
import numpy as py

a = np.array([1, 2 + 6j, 5, 3.5 + 5j])
print(a[np.iscomplex(a)])

In [ ]:
import numpy as np

x = np.arange(32).reshape(8, 4)
x[[4, 2, 1, 7]]

In [ ]:
import numpy as np

x = np.arange(32).reshape((8, 4))
x[[-4, -2, -1, -7]]

In [ ]:
import numpy as np

print(x)
print(x[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])])


In [ ]:
import numpy as np

a = np.arange(8)
print(a, '\n')

b = a.reshape(4, 2)
print(b, '\n')

In [ ]:
import numpy as np

a = np.arange(4).reshape(2, 2)
for row in a:
    print(row)

In [ ]:
import numpy as np

a = np.arange(4).reshape(2, 2)
for row in a:
    print(row)

for item in a.flat:
    print(item)

In [ ]:
import numpy as np

a = np.arange(8).reshape(2, 4)
print(a)

print(a.flatten())
print(a.flatten(order='F'))

In [ ]:
import numpy as np

a = np.arange(8).reshape(2, 4)
print(a)

print(a.ravel())

print(a.ravel(order='F'))

In [ ]:
import numpy as np

a = np.arange(12).reshape(3, 4)
print(a)

print(np.transpose(a))

In [ ]:
import numpy as np

a = np.arange(12).reshape(3, 4)

print(a)
print(a.T)


In [ ]:
import numpy as np

a = np.arange(8).reshape(2, 2, 2)
print(a)
print(np.rollaxis(a, 2))
print(np.rollaxis(a, 2, 1))

In [ ]:
import numpy as np

a = np.arange(8).reshape(2, 2, 2)
print(a)
print(np.swapaxes(a, 2, 0))

In [ ]:
import numpy as np

x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])

b = np.broadcast(x, y)
r, c = b.iters

print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))

In [ ]:
import numpy as np

a = np.arange(4).reshape(1, 4)

print(a)

print(np.broadcast_to(a, (4, 4)))

In [ ]:
import numpy as np

x = np.array(([1, 2], [3, 4]))

print(x)
y = np.expand_dims(x, axis=0)
print(y)
print(x.shape, y.shape)

y = np.expand_dims(x, axis=1)
print(y)
print(x.ndim, y.ndim)

print(x.shape, y.shape)

In [ ]:
import numpy as np

x = np.arange(9).reshape(1, 3, 3)

print('数组 x：')
print(x)
print('\n')
y = np.squeeze(x)

print('数组 y：')
print(y)
print('\n')

print('数组 x 和 y 的形状：')
print(x.shape, y.shape)

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])

print('第一个数组：')
print(a)
print('\n')

b = np.array([[5, 6], [7, 8]])
print('第二个数组：')
print(b)
print('\n')

print('沿着 0 连接两个数组：')
print(np.concatenate((a, b)))
print('\n')

print('沿着 1 连接两个数组：')
print(np.concatenate((a, b), axis=1))

In [ ]:
import numpy as py

a = np.array([[1, 2], [3, 4]])

print('第一个数组：')
print(a)
print('\n')

b = np.array([[5, 6], [7, 8]])

print('第二个数组：')
print(b)
print('\n')

print('沿着 0 堆叠两个数组：')
print(np.stack((a, b), 0))
print('\n')

print('沿轴 1 堆叠两个数组：')
print(np.stack((a, b), 1))

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])

print('第一个数组：')
print(a)
print('\n')
b = np.array([[5, 6], [7, 8]])

print('第二个数组：')
print(b)
print('\n')

print('水平堆叠')
c = np.hstack((a, b))
print(c)
print('\n')

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])

print('第一个数组：')
print(a)
print('\n')

b = np.array([[5, 6], [7, 8]])
print('第二个数组：')
print(b)
print('\n')

print('数值堆叠：')
c = np.vstack((a, b))
print(c)

In [ ]:
import numpy as np

a = np.arange(9)

print('第一个数组：')
print(a)
print('\n')

print('将数组分为三个大小相同的子数组：')
b = np.split(a, 3)
print(b)
print('\n')

print('将数组在一维数组中表面的位置分隔：')
b = np.split(a, [4, 7])
print(b)

In [ ]:
import numpy as np

harr = np.floor(10 * np.random.random((2, 6)))
print('原数组：')
print(harr)

print('拆分后：')
print(np.hsplit(harr, 3))


In [ ]:
import numpy as np

a = np.arange(16).reshape(4, 4)

print('原数组：')
print(a)
print('\n')

print('竖直分割：')
b = np.vsplit(a, 2)
print(b)


In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print('第一个数组：')
print(a)
print('\n')

print('第一个数组的形状：')
print(a.shape)
print('\n')

b = np.resize(a, (3, 2))
print('第二个数组：')
print(b)
print('\n')

print('第二个数组的形状：')
print(b.shape)
print('\n')

print('修改第二个数组的大小：')
b = np.resize(a, (3, 3))
print(b)

In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print('第一个数组：')
print(a)
print('\n')

print('向数组添加元素：')
print(np.append(a, [7, 8, 9]))
print('\n')

print('沿轴 0 添加元素：')
print(np.append(a, [[7, 8, 9]], axis=0))
print('\n')

print('沿轴 1 添加元素：')
print(np.append(a, [[5, 5, 5], [7, 8, 9]], axis=1))

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])

print('原数组：')
print(a)
print('\n')

print('未传递 Axis 参数，在插入之前数字会被展开')
print(np.insert(a, 3, [11, 12]))
print('\n')

print('传递了 axis 参数，会广播值数值来配输入数组')
print('沿着 0 广播：')
print(np.insert(a, 1, [11], axis=0))
print('\n')

print('沿轴 1 广播：')
print(np.insert(a, 1, 11, axis=1))

In [ ]:
import numpy as np

a = np.arange(12).reshape(3, 4)

print('第一个数组：')
print(a)
print('\n')

print('未传递 axis 参数，在插入之前输入输入会被展开')
print(np.delete(a, 5))
print('\n')

print('删除第二列：')
print(np.delete(a, 1, axis=1))
print('\n')

print('包含从数组中删除的替代值的切片：')
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np.delete(a, np.s_[::2]))

In [ ]:
import numpy as np

a = np.array([5, 2, 6, 2, 7, 5, 6, 8, 2, 90])

print('第一个数组：')
print(a)
print('\n')

print('第一个数组的去重值：')
u = np.unique(a)
print(u)
print('\n')

print('去重数组的索引数组：')
u, indices = np.unique(a, return_index=True)
print(indices)
print('\n')

print('我们可以看到每个和原数组下标对应的数值：')
print(a)
print('\n')

print('去重数组的下标：')
u, indices = np.unique(a, return_inverse=True)
print(u)
print('\n')

print('下标为：')
print(indices)
print('\n')

print('使用下标重构原数组：')
print(u[indices])
print('\n')

print('返回去重元素的重复数量：')
u, indices = np.unique(a, return_index=True)
print(u)
print(indices)

In [ ]:
import numpy as np

a = np.arange(6).reshape(3, 2)

print('初始数组：', '\n', a, '\n')
print('迭代数组：')

for x in np.nditer(a):
    print(x, end='.')


In [ ]:
a = np.arange(6).reshape(3, 2)

print('初始数组：', '\n', a, '\n')
print('以F形式进行迭代：')

for i in np.nditer(a, order='F'):
    print(i, end=',')

print('\n')

print('以 C 形式进行迭代：')
for i in np.nditer(a, order='C'):
    print(i, end=',')

In [ ]:
import numpy as np

a = np.arange(0, 60, 5).reshape(3, 4)

print('原始数组时：')
print(a)
print('\n')

for x in np.nditer(a, op_flags=['readwrite']):  #%%
    import numpy as np

In [ ]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [ ]:
% % time
for _ in range(20):
    my_arr2 = my_arr * 2


In [ ]:
% % time
for _ in range(20):
    my_list2 = [x * 2 for x in my_list]


In [ ]:
def py_sum():
    a = [0, 1, 2, 3, 4]
    b = [9, 8, 7, 6, 5]
    c = []
    for i in range(len(a)):
        c.append(a[i] ** 2 + b[i] ** 3)
    return c


print(py_sum())

In [ ]:
import numpy as np


def np_sum():
    a = np.array([0, 1, 2, 3, 4])
    b = np.array([9, 8, 7, 6, 5])
    c = a ** 2 + b ** 3
    return c


print(np_sum())


In [ ]:
a = np.array([[0, 1, 2, 3, 4], [9, 8, 7, 6, 5]])
a

In [ ]:
np.array([[0, 1, 2, 3, 4], [9, 8, 7, 6, 5]])

In [ ]:
import numpy as np

a = np.array([[0, 1, 2, 3, 4], [9, 8, 7, 6, 5]])
print(a.ndim, a.shape, a.size, a.dtype, a.itemsize)


In [ ]:
x = np.array([1, 2, 3, 4])
x


In [ ]:
x = np.array((1, 2, 3, 4))
x


In [ ]:
x = np.array([(1, 2, 3, 4), (1, 2, 3, 8)])
x


In [ ]:
import numpy as np

np.empty([3, 2], dtype=int)

In [ ]:
np.linspace(1, 21, 9, endpoint=True, dtype=int)

In [ ]:
np.logspace(0, 9, 10, base=3, dtype=np.float16)


In [ ]:
import numpy as np

a = np.linspace(1, 20, 9, endpoint=False, dtype=int)
b = np.logspace(0, 9, 10, base=2, dtype=int)
c = np.concatenate((a, b))

In [ ]:
import numpy as np

a = np.ones((2, 3, 4), dtype=np.int32)
a.reshape((3, 8))

In [ ]:
import numpy as np

a = np.ones((2, 3, 4), dtype=np.int32)

a.resize((3, 8))
a


In [ ]:
import numpy as np

a = np.array(
    [
        [[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]],
        [[2, 2, 2, 2], [2, 2, 2, 2], [2, 2, 2, 2]]
    ]
)

a.swapaxes(0, 1)

In [ ]:
import numpy as np

a = np.array(
    [
        [[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]],
        [[2, 2, 2, 2], [2, 2, 2, 2], [2, 2, 2, 2]]
    ]
)

a.flatten()

In [ ]:
import numpy as np

a = np.ones((2, 3, 4), dtype=np.int32)
a

In [ ]:
import numpy as np

a = np.ones((2, 3, 4), dtype=np.int32)

In [ ]:
import numpy as np

a = np.ones((2, 3, 4), dtype=np.int32)
b = a.astype(np.float)

b

In [ ]:
import numpy as np

a = np.full((2, 3, 4), 25, dtype=np.int32)
a


In [ ]:
import numpy as np

a = np.full((2, 3, 4), 25, dtype=np.int32)
a

a.tolist()


In [ ]:
import numpy as np

data = np.array([1, 2, 3])
print('输出数组：', data)
print(data[0], data[1], data[0:2], data[1:])

In [ ]:
import numpy as np

data = np.array([1, 2, 3])
print(data.max(), data.min(), data.sum())

In [ ]:
import numpy as np

data = np.array([[1, 2], [3, 4], [5, 6]])
print(data)
print(data[0, 1])
print(data[1:3])
print(data[0:2, 0])

In [ ]:
import numpy as np

data = np.array([[1, 2], [3, 4], [5, 6]])
print(data.max(), data.min(), data.sum())


In [ ]:
print(data.max(axis=0), data.max(axis=1))

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 4], [5, 6]])
y = x[[0, 1, 2], [0, 1, 0]]
print(x, y)


In [ ]:
import numpy as np

x = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [9, 10, 11]
])

rows = np.array([[0, 0], [3, 3]])
cols = np.array([[0, 2], [0, 2]])

x[rows, cols]

In [ ]:
import numpy as py

x = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
    [9, 10, 11]
])
print(x[x > 5])

In [ ]:
import numpy as py

a = np.array([np.nan, 1, 2, np.nan, 3, 4, 5])
print(a[~np.isnan(a)])

In [ ]:
import numpy as py

a = np.array([1, 2 + 6j, 5, 3.5 + 5j])
print(a[np.iscomplex(a)])

In [ ]:
import numpy as np

x = np.arange(32).reshape(8, 4)
x[[4, 2, 1, 7]]

In [ ]:
import numpy as np

x = np.arange(32).reshape((8, 4))
x[[-4, -2, -1, -7]]

In [ ]:
import numpy as np

print(x)
print(x[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])])


In [ ]:
import numpy as np

a = np.arange(8)
print(a, '\n')

b = a.reshape(4, 2)
print(b, '\n')

In [ ]:
import numpy as np

a = np.arange(4).reshape(2, 2)
for row in a:
    print(row)

In [ ]:
import numpy as np

a = np.arange(4).reshape(2, 2)
for row in a:
    print(row)

for item in a.flat:
    print(item)

In [ ]:
import numpy as np

a = np.arange(8).reshape(2, 4)
print(a)

print(a.flatten())
print(a.flatten(order='F'))

In [ ]:
import numpy as np

a = np.arange(8).reshape(2, 4)
print(a)

print(a.ravel())

print(a.ravel(order='F'))

In [ ]:
import numpy as np

a = np.arange(12).reshape(3, 4)
print(a)

print(np.transpose(a))

In [ ]:
import numpy as np

a = np.arange(12).reshape(3, 4)

print(a)
print(a.T)


In [ ]:
import numpy as np

a = np.arange(8).reshape(2, 2, 2)
print(a)
print(np.rollaxis(a, 2))
print(np.rollaxis(a, 2, 1))

In [ ]:
import numpy as np

a = np.arange(8).reshape(2, 2, 2)
print(a)
print(np.swapaxes(a, 2, 0))

In [ ]:
import numpy as np

x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])

b = np.broadcast(x, y)
r, c = b.iters

print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))
print(next(r), next(c))

In [ ]:
import numpy as np

a = np.arange(4).reshape(1, 4)

print(a)

print(np.broadcast_to(a, (4, 4)))

In [ ]:
import numpy as np

x = np.array(([1, 2], [3, 4]))

print(x)
y = np.expand_dims(x, axis=0)
print(y)
print(x.shape, y.shape)

y = np.expand_dims(x, axis=1)
print(y)
print(x.ndim, y.ndim)

print(x.shape, y.shape)

In [ ]:
import numpy as np

x = np.arange(9).reshape(1, 3, 3)

print('数组 x：')
print(x)
print('\n')
y = np.squeeze(x)

print('数组 y：')
print(y)
print('\n')

print('数组 x 和 y 的形状：')
print(x.shape, y.shape)

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])

print('第一个数组：')
print(a)
print('\n')

b = np.array([[5, 6], [7, 8]])
print('第二个数组：')
print(b)
print('\n')

print('沿着 0 连接两个数组：')
print(np.concatenate((a, b)))
print('\n')

print('沿着 1 连接两个数组：')
print(np.concatenate((a, b), axis=1))

In [ ]:
import numpy as py

a = np.array([[1, 2], [3, 4]])

print('第一个数组：')
print(a)
print('\n')

b = np.array([[5, 6], [7, 8]])

print('第二个数组：')
print(b)
print('\n')

print('沿着 0 堆叠两个数组：')
print(np.stack((a, b), 0))
print('\n')

print('沿轴 1 堆叠两个数组：')
print(np.stack((a, b), 1))

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])

print('第一个数组：')
print(a)
print('\n')
b = np.array([[5, 6], [7, 8]])

print('第二个数组：')
print(b)
print('\n')

print('水平堆叠')
c = np.hstack((a, b))
print(c)
print('\n')

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])

print('第一个数组：')
print(a)
print('\n')

b = np.array([[5, 6], [7, 8]])
print('第二个数组：')
print(b)
print('\n')

print('数值堆叠：')
c = np.vstack((a, b))
print(c)

In [ ]:
import numpy as np

a = np.arange(9)

print('第一个数组：')
print(a)
print('\n')

print('将数组分为三个大小相同的子数组：')
b = np.split(a, 3)
print(b)
print('\n')

print('将数组在一维数组中表面的位置分隔：')
b = np.split(a, [4, 7])
print(b)

In [ ]:
import numpy as np

harr = np.floor(10 * np.random.random((2, 6)))
print('原数组：')
print(harr)

print('拆分后：')
print(np.hsplit(harr, 3))


In [ ]:
import numpy as np

a = np.arange(16).reshape(4, 4)

print('原数组：')
print(a)
print('\n')

print('竖直分割：')
b = np.vsplit(a, 2)
print(b)


In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print('第一个数组：')
print(a)
print('\n')

print('第一个数组的形状：')
print(a.shape)
print('\n')

b = np.resize(a, (3, 2))
print('第二个数组：')
print(b)
print('\n')

print('第二个数组的形状：')
print(b.shape)
print('\n')

print('修改第二个数组的大小：')
b = np.resize(a, (3, 3))
print(b)

In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print('第一个数组：')
print(a)
print('\n')

print('向数组添加元素：')
print(np.append(a, [7, 8, 9]))
print('\n')

print('沿轴 0 添加元素：')
print(np.append(a, [[7, 8, 9]], axis=0))
print('\n')

print('沿轴 1 添加元素：')
print(np.append(a, [[5, 5, 5], [7, 8, 9]], axis=1))

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])

print('原数组：')
print(a)
print('\n')

print('未传递 Axis 参数，在插入之前数字会被展开')
print(np.insert(a, 3, [11, 12]))
print('\n')

print('传递了 axis 参数，会广播值数值来配输入数组')
print('沿着 0 广播：')
print(np.insert(a, 1, [11], axis=0))
print('\n')

print('沿轴 1 广播：')
print(np.insert(a, 1, 11, axis=1))

In [ ]:
import numpy as np

a = np.arange(12).reshape(3, 4)

print('第一个数组：')
print(a)
print('\n')

print('未传递 axis 参数，在插入之前输入输入会被展开')
print(np.delete(a, 5))
print('\n')

print('删除第二列：')
print(np.delete(a, 1, axis=1))
print('\n')

print('包含从数组中删除的替代值的切片：')
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np.delete(a, np.s_[::2]))

In [ ]:
import numpy as np

a = np.array([5, 2, 6, 2, 7, 5, 6, 8, 2, 90])

print('第一个数组：')
print(a)
print('\n')

print('第一个数组的去重值：')
u = np.unique(a)
print(u)
print('\n')

print('去重数组的索引数组：')
u, indices = np.unique(a, return_index=True)
print(indices)
print('\n')

print('我们可以看到每个和原数组下标对应的数值：')
print(a)
print('\n')

print('去重数组的下标：')
u, indices = np.unique(a, return_inverse=True)
print(u)
print('\n')

print('下标为：')
print(indices)
print('\n')

print('使用下标重构原数组：')
print(u[indices])
print('\n')

print('返回去重元素的重复数量：')
u, indices = np.unique(a, return_index=True)
print(u)
print(indices)

In [ ]:
import numpy as np

a = np.arange(6).reshape(3, 2)

print('初始数组：', '\n', a, '\n')
print('迭代数组：')

for x in np.nditer(a):
    print(x, end='.')


In [ ]:
a = np.arange(6).reshape(3, 2)

print('初始数组：', '\n', a, '\n')
print('以F形式进行迭代：')

for i in np.nditer(a, order='F'):
    print(i, end=',')

print('\n')

print('以 C 形式进行迭代：')
for i in np.nditer(a, order='C'):
    print(i, end=',')

In [ ]:
import numpy as np

a = np.arange(0, 60, 5).reshape(3, 4)

print('原始数组时：')
print(a)
print('\n')

for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = 2 * x
print('修改后的数组是：', '\n', a)

In [ ]:
import numpy as np

a = np.arange(0, 60, 5).reshape(3, 4)
print('原始数组是：', '\n', a, '\n')

print('修改后的数组是：')
for x in np.nditer(a, flags=['external_loop'], order='F'):
    print(x, end='.')
print('\n')
for x in np.nditer(a, flags=['f_index'], order='F'):
    print(x, end=',')

In [ ]:
import numpy as np

a = np.arange(0, 60, 5).reshape(3, 4)
print('第一个数组为：', '\n', a)

print('第二个数组为：')
b = np.array([1, 2, 3, 4], dtype=int)
print(b, '\n')

print('修改后的数组为：')
for x, y in np.nditer([a, b]):
    print(f'{x}:{y}', end=',')

In [ ]:
import numpy as np

data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([1, 1])

data + ones_row


In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
np.save('outfile.npy', a)
np.save('outfile2', a)